<?php

/**
 * @file
 * Contains my_module_browser_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_module_browser_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_module_browser_test module.
    case 'help.page.my_module_browser_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function my_module_browser_test_theme() {
  return [
    'my_module_browser_test' => [
      'render element' => 'children',
    ],
  ];
}
