<?php

/**
 * @file
 * Contains multi_pass_update.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function multi_pass_update_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the multi_pass_update module.
    case 'help.page.multi_pass_update':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function multi_pass_update_theme() {
  return [
    'multi_pass_update' => [
      'render element' => 'children',
    ],
  ];
}
