<?php

/**
 * @file
 * Contains my_dynamic_link.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_dynamic_link_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_dynamic_link module.
    case 'help.page.my_dynamic_link':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function my_dynamic_link_theme() {
  return [
    'my_dynamic_link' => [
      'render element' => 'children',
    ],
  ];
}
