<?php

/**
 * @file
 * Contains my_custom_view_filter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_custom_view_filter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_custom_view_filter module.
    case 'help.page.my_custom_view_filter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_data_alter().
 */
function my_custom_view_filter_views_data_alter(array &$data) {
  $data['node_field_data']['node_type_filter'] = array(
    'title' => t('Enhanced node type filter'),
    'filter' => array(
      'title' => t('Enhanced node type filter'),
      'help' => t('Provides a custom filter for nodes by their type.'),
      'field' => 'type',
      'id' => 'string'
    ),
  );

  $data['node_field_data']['nodes_titles'] = array(
    'title' => t('Node titles'),
    'filter' => array(
      'title' => t('Node titles'),
      'help' => t('Specify a list of titles a node can have.'),
      'field' => 'title',
      'id' => 'my_custom_view_filter_node_titles'
    ),
  );
}

/**
 * Implements hook_theme().
 */
function my_custom_view_filter_theme() {
  return [
    'my_custom_view_filter' => [
      'render element' => 'children',
    ],
  ];
}
