<?php

namespace Drupal\my_service_decorator;

/**
 * Class DefaultService.
 */
class DefaultServiceOverride extends DefaultService {

  public function getName(): string
  {
    return 'ADAM MA KOTA' .parent::getName(); // TODO: Change the autogenerated stub
  }


}
