<?php

/**
 * @file
 * Contains js_ajax_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function js_ajax_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the js_ajax_api module.
    case 'help.page.js_ajax_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function js_ajax_api_theme() {
  return [
    'js_ajax_api' => [
      'render element' => 'children',
    ],
  ];
}
