<?php

/**
 * @file
 * Contains js_ajax_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function js_ajax_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the js_ajax_api module.
    case 'help.page.js_ajax_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function js_ajax_api_theme() {
  return [
    'js_ajax_api' => [
      'variables' => [
        'name' => NULL,
      ],
    ],
  ];
}


/**
 * Implements hook_form_alter().
 */
function js_ajax_api_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if ($form_id=='node_article_form') {
    $form['field_my_text_simple']['widget'][0]['value']['#value'] = 'adam ma kota';

    $param = (int) \Drupal::request()->get('keys');
    $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($param);
    $article_cat = \Drupal::entityTypeManager()->getStorage('node')->load(9);

    $form['field_tags']['widget']['target_id']['#default_value'] = [$term];
    //for autocomeplete
    //$form['field_article_category']['widget'][0]['target_id']['#default_value'] = $article_cat;
    //for select
    $form['field_article_category']['widget']['#default_value'] = [$article_cat->id()];
    //dump($form['field_tags']['widget']['target_id']['#default_value']);
      //$form['field_tags']['und']['#default_value'] = array(1);
  }
}