simple_configuration.simple_configuration_setting_form:
  path: 'admin/config/media/simple-config'
  defaults:
    _form: '\Drupal\simple_configuration\Form\SettingForm'
    _title: 'SettingForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE
