<?php

/**
 * @file
 * Contains entity_queries.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_queries_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_queries module.
    case 'help.page.entity_queries':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function entity_queries_theme() {
  return [
    'entity_queries' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_entity_view().
 */
function entity_queries_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getEntityTypeId() == 'node' && $view_mode == 'tiles') {

    /*$build['disclaimer'] = [
      '#markup' => t('The content provided is for general information purposes only.'),
      '#weight' => 100
    ];*/
  }
  if ($display->getComponent('disclaimer')) {
    $build['disclaimer'] = [
      '#markup' => t('The content provided is for general information purposes only.'),
    ];
  }
}

/**
 * For view fields
 */

/**
 * Implements hook_views_data_alter().
 */
function entity_queries_views_data_alter(array &$data) {
  $data['node_field_data']['disclaimer'] = [
    'title' => t('Disclaimer'),
    'help' => t('Shows a disclaimer message'),
    'field' => [
      'id' => 'custom',
    ],
  ];
}


/**
 * CREATE PSEUDOFIELD
 */
/**
 * Implements hook_entity_extra_field_info().
 */
function entity_queries_entity_extra_field_info() {
  $extra = [];

  foreach (\Drupal\node\Entity\NodeType::loadMultiple() as $bundle) {
    $extra['node'][$bundle->id()]['display']['disclaimer'] = [
      'label' => t('Disclaimer'),
      'description' => t('A general disclaimer'),
      'weight' => 100,
      'visible' => TRUE,
    ];
  }

  return $extra;
}