<?php

/**
 * @file
 * Contains entity_queries.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_queries_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_queries module.
    case 'help.page.entity_queries':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function entity_queries_theme() {
  return [
    'entity_queries' => [
      'render element' => 'children',
    ],
  ];
}
