products.importer.*:
  type: config_entity
  label: 'Importer config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    url:
      type: uri
      label: 'Uri'
    plugin:
      type: string
      label: 'Plugin Id'
    update_existing:
      type: boolean
      label: 'Whether to update existing products'
    source:
      type: string
      label: 'The source of the products'
