<?php

/**
 * @file
 * Contains user_status_online.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\User;
use Drupal\user_status_online\Status;
use Drupal\user_status_online\StatusStrategy\AbsentStrategy;
use Drupal\user_status_online\StatusStrategy\OfflineStrategy;
use Drupal\user_status_online\StatusStrategy\OnlineStrategy;

/**
 * Implements hook_help().
 */
function user_status_online_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_status_online module.
    case 'help.page.user_status_online':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module provides View Field to views and Pseudo Field to display mode and display if user is online or not') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_entity_extra_field_info().
 */
function user_status_online_entity_extra_field_info() {

  $extra = [];

  $extra['user']['user']['display']['user_status_online'] = [
    'label'       => t('Online Status'),
    'description' => t("Show the user's online status"),
    'weight'      => 100,
    'visible'     => TRUE,
  ];

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function user_status_online_user_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {

  if ($display->getComponent('user_status_online')) {

    $build['user_status_online'] = [
      '#theme'         => 'user_status_online',
      '#label'         => t('Online Status'),
      '#label_display' => 'inline',
      '#uid'           => $entity->id(),
      '#view_mode'     => $view_mode,
      '#cache' => [
        'max-age' => 0,
      ]

    ];
  }
}

/**
 * Implements hook_theme().
 */
function user_status_online_theme($existing, $type, $theme, $path) {

  return [
    'user_status_online' => [
      'variables' => [
        'label'         => NULL,
        'label_display' => NULL,
        'uid'           => NULL,
        'view_mode'     => NULL,
      ],
    ],
  ];
}

/**
 * Implement template_preprocess_HOOK()
 * @param $variables
 */
function template_preprocess_user_status_online(&$variables)
{
  $uid = (int) $variables['uid'];

  $user = User::load($uid);
  $statusManager = new Status($user,\Drupal::requestStack());
  $statusManager->addStrategy(new OnlineStrategy());
  $statusManager->addStrategy(new OfflineStrategy());
  $statusManager->addStrategy(new AbsentStrategy());
  $variables['status'] = t($statusManager->getStatus());

}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function user_status_online_theme_suggestions_user_status_online(array $variables) {

  $suggestions = [];

  $suggestions[] = $variables['theme_hook_original'] . '__' . $variables['uid'] . '__' . $variables['view_mode'];
  $suggestions[] = $variables['theme_hook_original'] . '__' . $variables['uid'];
  $suggestions[] = $variables['theme_hook_original'] . '__' . $variables['view_mode'];

  return $suggestions;
}