<?php

/**
 * @file
 * Contains address_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function address_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the address_field module.
    case 'help.page.address_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Defines a simple address field type.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function address_field_theme() {
  return [
    'address_field' => [
      'render element' => 'children',
    ],
  ];
}
