<?php

/**
 * @file
 * Contains text_css_field.module.
 */

/**
 * Implements hook_theme().
 */
function text_css_field_theme($existing, $type, $theme, $path) {
  return [
    'text_css_header' => [
      'variables' => [
        'items' => NULL,
      ],
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_text_css_header(&$variables) {
// Do your custom preprocess logic here for the field.
// Add custom variables if you want them to be available in twig template:
// $variables['custom_variable'] = "Some data";
}


/**
 * Implements hook_preprocess_views_view_field().
  */
function text_css_field_preprocess_views_view_field(&$variables) {
  $field = $variables['field'];
  if ($field->field == 'text_css_content') {
    $result = $field->options['text_css_content'];
    $variables['output'] = Drupal\Core\Render\Markup::create($result); // saving value
  }
}
