<?php

/**
 * @file
 * Contains my_menu.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_menu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_menu module.
    case 'help.page.my_menu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function my_menu_theme() {
  return [
    'my_menu' => [
      'render element' => 'children',
    ],
    'mytest' => [
      'variables' => [
        'params' => NULL,

      ],
      'template' => 'my-test',
    ],
  ];
}
