<?php

/**
 * @file
 * Contains attachment_library.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function attachment_library_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the attachment_library module.
    case 'help.page.attachment_library':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function attachment_library_theme($existing, $type, $theme, $path) {
  $variables = [
    'attachment_library' => [
      'variables' => [
        'some_variable' => NULL,

      ],
    ],
  ];
  return $variables;
}

/**
 * @param array $attachments
 * another way to attach library
 */

/**
 * @param array $attachments
 * this way
 */
function attachment_library_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'attachment_library/slick';
}


/**
 * @param $variables
 * or this way
 */
function attachment_library_preprocess_attachment_library(&$variables) {
  $variables['#attached']['library'][] =  'attachment_library/slick';
}