<?php

/**
 * @file
 * Sandwich module.
 */
use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function sandwich_theme() {
  return [
    'sandwich' => [
      'render element' => 'element',
    ],
    'sandwich_test' => [
      'variables' => [
        'service' => NULL,

      ],
    ]
  ];
}

function template_preprocess_sandwich_test(&$variables) {
  $variables['name'] = 'adam ma kota';
}

function sandwich_theme_suggestions_sandwich_test($variables) {
  return [
    'sandwitch__test__mojtest'
  ];
}
/**
 * Implements hook_theme_suggestions_sandwich().
 */
function sandwich_theme_suggestions_sandwich($variables) {
  return [
 //   'sandwich__' . strtolower(Html::cleanCssIdentifier($variables['name'])),
    ];
}



/**
 * Implements hook_theme_suggestions_sandwich_alter().
 */
function sandwich_theme_suggestions_sandwich_alter(&$suggestions, $variables) {
}

/**
 * Implements template_preprocess_sandwich().
 */
function template_preprocess_sandwich(&$variables) {
  //$variables['name'] = 'hehehe';
  $element = $variables['element'];
  $variables['name'] = $element['#name'];
  $variables['bread'] = $element['#bread'];
  $variables['cheese'] = $element['#cheese'];
  $variables['veggies'] = $element['#veggies'];
}

/**
 * Implements hook_preprocess_sandwich().
 */
function sandwich_preprocess_sandwich(&$variables) {
  //$variables['name']  = 'Kitten2';
  //dump($variables);
  //$variables['test'] = 'adam ma kota';
  //$variables['name'] = $variables['element']['#name'];
  $variables['cheese'] = 'dupa';




  //dump($variables);


}

function sandwich_preprocess_sandwich__chickado(&$variables) {
  //$variables['protein'] = 'dafasdfdsa';
}

function sandwich_preprocess_sandwich__test(&$variables) {
}
