<?php

/**
 * @file
 * Sandwich module.
 */
use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function sandwich_theme() {
  return [
    'sandwich' => [
      'render element' => 'element',
    ],
    'sandwich_test' => [
      'variables' => [
        'service' => NULL,

      ],
    ]
  ];
}

function template_preprocess_sandwich_test(&$variables) {
  $variables['name'] = 'adam ma kota';
}

function sandwich_theme_suggestions_sandwich_test($variables) {
  return [
    'sandwitch__test__mojtest'
  ];
}
/**
 * Implements hook_theme_suggestions_sandwich().
 */
function sandwich_theme_suggestions_sandwich($variables) {
  return [
 //   'sandwich__' . strtolower(Html::cleanCssIdentifier($variables['name'])),
    ];
}



/**
 * Implements hook_theme_suggestions_sandwich_alter().
 */
function sandwich_theme_suggestions_sandwich_alter(&$suggestions, $variables) {
}

/**
 * Implements template_preprocess_sandwich().
 */
function template_preprocess_sandwich(&$variables) {
  //$variables['name'] = 'hehehe';
  $element = $variables['element'];
  $variables['name'] = $element['#name'];
  $variables['bread'] = $element['#bread'];
  $variables['cheese'] = $element['#cheese'];
  $variables['veggies'] = $element['#veggies'];
 // $variables['attributes2'] = new \Drupal\Core\Template\Attribute($element['#attributes2']);
  $variables['isActive'] = $element['#isActive'];
  if ((bool) $variables['isActive']) {
    $variables['name'] = $variables['name'].' is active';
  }
}

/**
 * Implements hook_preprocess_sandwich().
 */
function sandwich_preprocess_sandwich(&$variables) {
  //$variables['name']  = 'Kitten2';
  //dump($variables);
  //$variables['test'] = 'adam ma kota';
  //$variables['name'] = $variables['element']['#name'];
  $variables['cheese'] = 'dupa';




  //dump($variables);


}

function sandwich_preprocess_sandwich__chickado(&$variables) {
  //$variables['protein'] = 'dafasdfdsa';
}

function sandwich_preprocess_sandwich__test(&$variables) {
}


/**
 * Implements hook_page_top().
 */
function sandwich_page_top(array &$page_top) {

  /*$render = [
    '#type' => 'sandwich',
    '#contextual_links' => [
      'sandwich' => [
        'route_parameters' => []
      ],
    ],

    '#attributes' => [
      'id' => 'best-sandwich2',
      'class' => ['menu--lefter', 'clearfix'],
    ],
    '#isActive' => false,


    '#cheese' => t('Gruyère'),
    '#veggies' => [
      t('Avocado'),
      t('Red onion'),
      t('Romaine'),
    ],
    '#protein' => t('Chicken'),

  ];

  $render['#name'] = t('Chickado');
  $page_top['sandwich'] = $render;*/
}