<?php

/**
 * @file
 * Contains form_validation_with_tdd.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\FileInterface;

/**
 * Implements hook_help().
 */
function form_validation_with_tdd_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the form_validation_with_tdd module.
    case 'help.page.form_validation_with_tdd':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}


/**
 * File Validation Callback
 *
 * @param \Drupal\file\FileInterface $file
 *   The file to be validate
 *
 * @return array
 *   List of validation issues, if any
 */
function form_validation_validate_csv(FileInterface $file) {
  /**
   * @var \Drupal\form_validation_with_tdd\CsvValidatorInterface $csvValidator
   */
  $csvValidator = Drupal::service('form_validation_with_tdd.csv_validator');
  return $csvValidator->validate($file);
}
