<?php

/**
 * @file
 * Contains my_crone.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_crone_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_crone module.
    case 'help.page.my_crone':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function my_crone_theme() {
  return [
    'my_crone' => [
      'render element' => 'children',
    ],
  ];
}

function test_cron_sample_cron_job() {
  $date = (new \DateTime())->format('Y-m-d h:i:s');
  $file = file_save_data((new \DateTime())->format('Y-m-d h:i:s'), "public://my_file_$date.txt", \Drupal\Core\File\FileSystemInterface::EXISTS_REPLACE);
}



