services:
  plugin.manager.importer:
    class: Drupal\products\Plugin\ImporterManager
    parent: default_plugin_manager
    arguments: ['@entity_type.manager']

  products.commands:
    class: Drupal\products\Commands\ProductCommands
    arguments: ['@plugin.manager.importer','@entity_type.manager']
    tags:
      - { name: drush.command }