<?php

/**
 * @file
 * Contains my_cache.module.
 */

use Drupal\Component\Utility\Random;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_cache_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_cache module.
    case 'help.page.my_cache':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function my_cache_theme() {
  return [
    'my_cache' => [
      'variables' => [
        'name' => NULL,
      ],
    ]
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function my_cache_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {

  if ($entity->bundle()=='article' && $view_mode == 'full') {
    $tags = $entity->getCacheTags();




  }
}


function my_cache_preprocess_breadcrumb(&$variables) {
  /*if (($node = \Drupal::routeMatch()->getParameter('node')) && $variables['breadcrumb']) {
    $variables['breadcrumb'][] = [
      'text' => $node->getTitle() //(new Random())->string(5)
    ];
    $variables['#cache']['contexts'][] = 'url.path';

    //dump($variables);
  }*/
}
function my_cache_preprocess_page_title(&$variables) {

  $node = \Drupal::request()->attributes->get('node');

  if ($node && $node->bundle() == 'article') {
    $variables['title'] = t('@title Review', ['@title' => $node->getTitle()]);
    //dump($variables);
    // $variables['#cache']['max-age'] = 0;
  }
}