<?php

/**
 * @file
 * Contains form_validation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\FileInterface;

/**
 * Implements hook_help().
 */
function form_validation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the form_validation module.
    case 'help.page.form_validation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * File Validation Callback
 *
 * @param \Drupal\file\FileInterface
 *
 * @return array
 *    List of validation issues if any.
 *
 */
function form_validation_validate_csv(FileInterface $file) {
  $errors = [];

}
