<?php


namespace Drupal\hello_world\Form;

use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Logger\LoggerChannelInterface;
use Drupal\hello_world\HelloWorldSalutation;
use Symfony\Component\DependencyInjection\ContainerInterface;

class MyClass extends ConfigFormBase{
  public $helloWorldSalutation;

  /**
   * @var LoggerChannelInterface
   */
  protected $logger;

  public function __construct(ConfigFactoryInterface $config_factory, LoggerChannelInterface $logger, HelloWorldSalutation $helloWorldSalutation) {
    parent::__construct($config_factory);
    $this->logger = $logger;
    $this->helloWorldSalutation = $helloWorldSalutation;
  }


  public function getHelloWorldSalutation() {
    return $this->helloWorldSalutation;
  }

  public function getFormId() {
    // TODO: Implement getFormId() method.
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  protected function getEditableConfigNames() {
    // TODO: Implement getEditableConfigNames() method.
  }

  public function save() {
    echo 'weszlo w klase';
  }

  /**
   * @inheritDoc
   */
  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('config.factory'),
      $container->get('hello_world.logger.channel.hello_world'),
      $container->get('hello_world.salutation')
    );
  }
}