<?php

/**
 * @file
 * Contains my_yaml_readable.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_yaml_readable_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_yaml_readable module.
    case 'help.page.my_yaml_readable':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function my_yaml_readable_theme() {
  return [
    'my_yaml_readable' => [
      'render element' => 'children',
    ],
  ];
}
