<?php

namespace Drupal\pw_bibliography_page\Controller;

use Drupal\Core\Controller\ControllerBase;
use Drupal\user\PrivateTempStoreFactory;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class DefaultController.
 */
class DefaultController extends ControllerBase {

  protected $tempStore;

  // Pass the dependency to the object constructor
  public function __construct(PrivateTempStoreFactory $temp_store_factory) {
    $this->tempStore = $temp_store_factory->get('pw_bibliography_page');
  }
/*
  // Uses Symfony's ContainerInterface to declare dependency to be passed to constructor
  public static function create(ContainerINterface $container) {
    return new static(
      $container->get('user.private_tempstore')
    );
  }*/

  public static function create(ContainerInterface $container) {
    return parent::create($container); // TODO: Change the autogenerated stub
  }

  public function hello($name) {
    return [
      '#type' => 'markup',
      '#markup' => $this->t('Implement method: hello with parameter(s): $name'),
    ];
  }

}
